
FROM oven/bun:1-alpine AS pruner
WORKDIR /app

COPY . .
RUN bunx turbo prune api --docker

FROM oven/bun:1-alpine AS installer
WORKDIR /app

COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/bun.lock ./bun.lock

RUN bun install --frozen-lockfile


FROM oven/bun:1-alpine AS builder
WORKDIR /app

COPY --from=installer /app/ .
COPY --from=pruner /app/out/full/ .


RUN cd packages/db && bunx prisma generate


RUN bunx turbo run build --filter=api


FROM oven/bun:1-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production


COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/bun.lock ./bun.lock

# Install production dependencies only
RUN bun install --frozen-lockfile --production


COPY --from=builder /app/packages ./packages
RUN cd /app/packages/db && bun install --frozen-lockfile --production

# Copy API build
COPY --from=builder /app/apps/api/dist ./apps/api/dist

# Copy API package.json
COPY --from=builder /app/apps/api/package.json ./apps/api/package.json

WORKDIR /app/apps/api

EXPOSE 5000

CMD ["bun", "run", "dist/index.js"]